# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_hash', models.CharField(max_length=512)),
                ('trans_type', models.CharField(max_length=512)),
                ('trans_from', models.CharField(max_length=512)),
                ('trans_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
